"""fourth

Revision ID: 9d58c8e8c84c
Revises: af71cb213a8a
Create Date: 2021-04-12 14:56:18.976779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d58c8e8c84c'
down_revision = 'af71cb213a8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microblog_posts', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'microblog_posts', 'microblog_posts', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'microblog_posts', type_='foreignkey')
    op.drop_column('microblog_posts', 'parent_id')
    # ### end Alembic commands ###
